%YAML:1.0
---
Markers:
  - Points:
    - freq: 6020
      x: -0.045
      y: -0.045
      z: 0.0
    - freq: 6200
      x: -0.045
      y: 0.0
      z: 0.0
    - freq: 6400
      x: -0.045
      y: 0.045
      z: 0.0
    - freq: 6620
      x: -0.0
      y: -0.045
      z: 0.0
    # - freq: 6800
    #   x: -0.0
    #   y: 0.0
    #   z: 0.0
    - freq: 7040
      x: -0.0
      y: 0.045
      z: 0.0
    - freq: 7240
      x: 0.045
      y: -0.045
      z: 0.0
    - freq: 7400
      x: 0.045
      y: 0.0
      z: 0.0
    - freq: 7640
      x: 0.045
      y: 0.045
      z: 0.0
    ID: 3
  - Points:
    - freq: 10000
      x: -0.045
      y: -0.045
      z: 0.0
    - freq: 10100
      x: -0.045
      y: 0.0
      z: 0.0
    - freq: 9800 # redo
      x: -0.045
      y: 0.045
      z: 0.0
    # - freq: 10600
    #   x: -0.0
    #   y: -0.045
    #   z: 0.0
    - freq: 9900
      x: -0.0
      y: 0.0
      z: 0.0
    - freq: 10520 # redo
      x: -0.0
      y: 0.045
      z: 0.0
    - freq: 10745 
      x: 0.045
      y: -0.045
      z: 0.0
    - freq: 10980
      x: 0.045
      y: 0.0
      z: 0.0
    - freq: 11110
      x: 0.045
      y: 0.045
      z: 0.0
    ID: 4
  - Points:
    - freq: 8000
      x: -0.045
      y: -0.045
      z: 0.0
    - freq: 8200
      x: -0.045
      y: 0.0
      z: 0.0
    - freq: 8400
      x: -0.045
      y: 0.045
      z: 0.0
    - freq: 8620
      x: -0.0
      y: -0.045
      z: 0.0
    # - freq: 8800
    #   x: -0.0
    #   y: 0.0
    #   z: 0.0
    - freq: 9000
      x: -0.0
      y: 0.045
      z: 0.0
    - freq: 9260
      x: 0.045
      y: -0.045
      z: 0.0
    - freq: 9440
      x: 0.045
      y: 0.0
      z: 0.0
    - freq: 9620
      x: 0.045
      y: 0.045
      z: 0.0
    ID: 1
  - Points:
    - freq: 5040
      x: -0.045
      y: -0.045
      z: 0.0
    - freq: 5100
      x: -0.045
      y: 0.0
      z: 0.0
    - freq: 5200
      x: -0.045
      y: 0.045
      z: 0.0
    - freq: 5376
      x: -0.0
      y: -0.045
      z: 0.0
    - freq: 5400
      x: -0.0
      y: 0.0
      z: 0.0
    # - freq: 13500 # not
    #   x: -0.0
    #   y: 0.045
    #   z: 0.0
    - freq: 5520
      x: 0.045
      y: -0.045
      z: 0.0
    - freq: 5640
      x: 0.045
      y: 0.0
      z: 0.0
    - freq: 5780
      x: 0.045
      y: 0.045
      z: 0.0
    ID: 2