%YAML:1.0
---
ExternalTriggers:
  channel_id: 0

CameraMatrix:
  data: [1713.702061319128, 0, 609.415041040968,
 0, 1713.702061319128, 358.6229632318172,
 0, 0, 1] 

DistCoeff:
  len: 5
  data: [-0.07870926337017053, 0.4799533437057025, -0.006716802951938758, -0.0003025954443558615, 0] 
